/* Banco de Dados */

CREATE DATABASE glamsync;
\c glamsync;

-- Create a table for users

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    location VARCHAR(100),
    photo TEXT,
    following INT DEFAULT 0,
    followers INT DEFAULT 0,
    created_user TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert sample data into users table

INSERT INTO users (name, username, email, location, photo, following, followers) 
VALUES 
    ('Alice Johnson', 'alicej', 'alice@example.com', 'New York', 'https://example.com/photos/alice.jpg', 10, 50),
    ('Bob Smith', 'bobsmith', 'bob@example.com', 'Los Angeles', 'https://example.com/photos/bob.jpg', 20, 100),
    ('Charlie Brown', 'charlieb', 'charlie@example.com', 'Chicago', 'https://example.com/photos/charlie.jpg', 15, 75),
    ('Diana Prince', 'dianap', 'diana@example.com', 'San Francisco', 'https://example.com/photos/diana.jpg', 30, 200),
    ('Ethan Hunt', 'ethanh', 'ethan@example.com', 'Miami', 'https://example.com/photos/ethan.jpg', 25, 150);

-- Create a table for posts

CREATE TABLE posts (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    categorie_id INTEGER REFERENCES categories(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    photo TEXT,
    likes INT DEFAULT 0,
    comments INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert sample data into posts table

INSERT INTO posts (user_id, content, categorie_id, photo, likes, comments) 
VALUES
-- Insert sample data into posts table

INSERT INTO posts (user_id, content, categorie_id, photo, likes, comments) 
VALUES
    (1, 'Look do dia: vestido floral e sandália confortável!', 1, 'https://example.com/photos/post1.jpg', 15, 3),
    (2, 'Acessórios fazem toda a diferença no visual.', 5, 'https://example.com/photos/post2.jpg', 22, 5),
    (3, 'Dica de maquiagem para o verão!', 4, 'https://example.com/photos/post3.jpg', 30, 7),
    (4, 'Chapéu estiloso para proteger do sol.', 2, 'https://example.com/photos/post4.jpg', 10, 2),
    (5, 'Sapatos confortáveis para o dia a dia.', 3, 'https://example.com/photos/post5.jpg', 18, 4);



CREATE TABLE chats (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO chats (user_id, message) VALUES
<<<<<<< HEAD
    (1, 'A moda é uma forma de liberdade. Liberte-se! 🌟'),
    (2, 'Qual sua peça favorita no guarda-roupa? 👗'),
    (3, 'Aposte em acessórios para transformar qualquer look! 💎'),
    (4, 'Estilo é a expressão da sua personalidade. Seja você! 🎨'),
    (5, 'Sustentabilidade na moda é o futuro. Vamos juntos! 🌱'),
    (6, 'Look do dia: conforto e estilo sempre! 😍'),
    (7, 'Já experimentou misturar estampas? Fica incrível! 🔥'),
    (8, 'Invista em peças que valorizam seu corpo e estilo. 💃'),
    (10, 'O segredo do estilo está nos detalhes. ⚡'),
    (11, 'Como escolher o jeans perfeito? Aposte no conforto! 👖'),
    (12, 'Você é mais clássico ou moderno na moda? 🤔'),
    (13, 'Acessórios grandes para um look poderoso! 💥'),
    (14, 'Look monocromático: simples e elegante. 🎯'),
    (15, 'Moda é arte, vista-se como uma obra-prima! 🖌️'),
    (16, 'Combinar cores pode ser divertido e estiloso! 🎨'),
    (17, 'Peças básicas são essenciais para qualquer guarda-roupa. 👕'),
    (18, 'Roupas confortáveis também podem ser estilosas! 🛋️'),
    (19, 'Já pensou em customizar suas roupas? 🎨'),
    (20, 'Invista em sapatos que combinam com tudo! 👟'),
    (21, 'A moda é para todos: encontre seu estilo único! 🌈'),
    (22, 'O que não pode faltar no seu closet? Conta pra gente! 🧥'),
    (23, 'Estampas florais são a cara da primavera! 🌸'),
    (24, 'Roupas feitas com amor fazem toda a diferença. ❤️'),
    (25, 'Aposte em looks que refletem sua autenticidade! ✨'),
    (26, 'Você prefere roupas neutras ou coloridas? 🤩'),
    (27, 'Look comfy para um dia relax, quem curte? 😌'),
    (28, 'Quer dicas para cuidar melhor das suas roupas? 🧼'),
    (29, 'Tem alguma peça xodó no seu armário? Conta! 🥰'),
    (30, 'Como escolher a bolsa ideal para o dia a dia? 👜'),
    (31, 'A moda é uma forma de expressão sem palavras! 🗣️'),
    (32, 'Roupas oversize são super estilosas e confortáveis! 😎'),
    (33, 'Qual seu acessório favorito para dar um up no look? 🕶️'),
    (34, 'Já usou roupas de brechó? Tem charme único! 🛍️'),
    (35, 'Mix de estampas: atrevimento com estilo! 🌟'),
    (36, 'Peças sustentáveis ajudam o planeta e o estilo! 🌍'),
    (37, 'Já fez um look inspirado em uma celebridade? Quem? 🌟'),
    (38, 'O que não pode faltar num look de festa? 🎉'),
    (39, 'Qual sua cor favorita para se vestir? ❤️🖤💙'),
    (40, 'Moda casual: conforto e estilo na medida certa! 👖👟'),
    (41, 'Os detalhes fazem toda a diferença no visual! 🔍'),
    (42, 'Você prefere acessórios grandes ou discretos? 💍'),
    (43, 'O que acha de apostar em estampas geométricas? 🔷'),
    (44, 'Já experimentou looks monocromáticos? São incríveis! 🎨'),
    (45, 'Como escolher o vestido ideal para uma ocasião especial? 👗'),
    (46, 'Roupas justas ou soltas: qual seu estilo? 🤔'),
    (47, 'Qual seu look preferido para um passeio no parque? 🌳'),
    (49, 'Qual peça você acha que é um investimento de moda? 💰'),
    (50, 'Look streetwear para quem curte estilo urbano! 🏙️'),
    (51, 'Já usou chapéu como acessório? Super estiloso! 🎩'),
    (52, 'Moda e conforto podem andar juntos sim! 💖'),
    (53, 'Qual a peça que você sempre repete no dia a dia? 🔄'),
    (54, 'Invista em roupas que fazem você se sentir confiante! 💪'),
    (55, 'O que acha de peças feitas com tecidos tecnológicos? 🧵'),
    (56, 'Já pensou em montar um guarda-roupa cápsula? 🎒'),
    (57, 'Looks coloridos para dar energia no seu dia! 🌈'),
    (58, 'Você prefere looks mais formais ou despojados? 👔🧢'),
    (59, 'Como combinar sapatos com a roupa? Dica rápida! 👠'),
    (60, 'Roupas de inverno que além de quentinhas são estilosas! ❄️'),
    (61, 'Qual seu estilo favorito de jaqueta? 🧥'),
    (62, 'Os acessórios certos transformam qualquer look! 💎'),
    (63, 'Já experimentou usar roupas com estampa animal? 🐆'),
    (64, 'Qual seu look ideal para um encontro? 💕'),
    (65, 'Dica: roupas de cores neutras combinam com tudo! ⚪⚫'),
    (66, 'Você prefere roupas feitas à mão ou industrializadas? 🧵'),
    (67, 'Como escolher o melhor jeans para seu corpo? 👖'),
    (68, 'Moda sustentável: pequenas atitudes, grande impacto! 🌱'),
    (69, 'Já fez customização DIY nas suas roupas? ✂️🎨'),
    (70, 'Qual peça vintage você gostaria de ter? 🕰️'),
    (71, 'Look para o verão: frescor e estilo na medida! ☀️'),
    (72, 'Você prefere estampas florais ou geométricas? 🌸🔷'),
    (73, 'Sapatos confortáveis para usar o dia todo! 👟'),
    (74, 'Aposte em acessórios que refletem sua personalidade! 🎭'),
    (75, 'Qual peça é seu verdadeiro “curinga”? 🎴'),
    (76, 'Você gosta de moda minimalista? 👌'),
    (77, 'Como escolher um bom blazer para ocasiões formais? 🤵'),
    (78, 'Qual é a peça que você gostaria de reinventar? 🔄'),
    (79, 'Dicas para combinar estampas sem errar! 🎨'),
    (80, 'Qual sua opinião sobre fast fashion? ♻️'),
    (81, 'Você tem um look favorito para sair com amigos? 🍹'),
    (82, 'Já usou alguma peça inspirada em outra cultura? 🌍'),
    (83, 'Looks para dias chuvosos com estilo! ☔'),
    (84, 'Você prefere bolsas grandes ou pequenas? 🎒👜'),
    (85, 'Qual seu acessório indispensável para o inverno? 🧣'),
    (86, 'Como usar roupas oversize sem perder o estilo? 😎'),
=======
    (1, 'A moda é uma forma de liberdade. Liberte-se! '),
    (2, 'Qual sua peça favorita no guarda-roupa? '),
    (3, 'Aposte em acessórios para transformar qualquer look! '),
    (4, 'Estilo é a expressão da sua personalidade. Seja você! '),
    (5, 'Sustentabilidade na moda é o futuro. Vamos juntos! '),
    (6, 'Look do dia: conforto e estilo sempre! '),
    (7, 'Já experimentou misturar estampas? Fica incrível! '),
    (8, 'Invista em peças que valorizam seu corpo e estilo. '),
    (9, 'Moda vintage está super em alta! Já usou? '),
    (10, 'O segredo do estilo está nos detalhes.'),
    (11, 'Como escolher o jeans perfeito? Aposte no conforto!'),
    (12, 'Você é mais clássico ou moderno na moda?'),
    (13, 'Acessórios grandes para um look poderoso!'),
    (14, 'Look monocromático: simples e elegante.'),
    (15, 'Moda é arte, vista-se como uma obra-prima!'),
    (16, 'Combinar cores pode ser divertido e estiloso!'),
    (17, 'Peças básicas são essenciais para qualquer guarda-roupa.'),
    (18, 'Roupas confortáveis também podem ser estilosas!'),
    (19, 'Já pensou em customizar suas roupas?'),
    (20, 'Invista em sapatos que combinam com tudo!'),
    (21, 'A moda é para todos: encontre seu estilo único!'),
    (22, 'O que não pode faltar no seu closet? Conta pra gente!'),
    (23, 'Estampas florais são a cara da primavera!'),
    (24, 'Roupas feitas com amor fazem toda a diferença.'),
    (25, 'Aposte em looks que refletem sua autenticidade!'),
    (26, 'Você prefere roupas neutras ou coloridas?'),
    (27, 'Look comfy para um dia relax, quem curte?'),
    (28, 'Quer dicas para cuidar melhor das suas roupas?'),
    (29, 'Tem alguma peça xodó no seu armário? Conta!'),
    (30, 'Como escolher a bolsa ideal para o dia a dia?'),
    (31, 'A moda é uma forma de expressão sem palavras!'),
    (32, 'Roupas oversize são super estilosas e confortáveis!'),
    (33, 'Qual seu acessório favorito para dar um up no look?'),
    (34, 'Já usou roupas de brechó? Tem charme único!'),
    (35, 'Mix de estampas: atrevimento com estilo!'),
    (36, 'Peças sustentáveis ajudam o planeta e o estilo!'),
    (37, 'Já fez um look inspirado em uma celebridade? Quem?'),
    (38, 'O que não pode faltar num look de festa?'),
    (39, 'Qual sua cor favorita para se vestir?'),
    (40, 'Moda casual: conforto e estilo na medida certa! '),
    (41, 'Os detalhes fazem toda a diferença no visual!'),
    (42, 'Você prefere acessórios grandes ou discretos?'),
    (43, 'O que acha de apostar em estampas geométricas?'),
    (44, 'Já experimentou looks monocromáticos? São incríveis!'),
    (45, 'Como escolher o vestido ideal para uma ocasião especial?'),
    (46, 'Roupas justas ou soltas: qual seu estilo?'),
    (47, 'Qual seu look preferido para um passeio no parque?'),
    (48, 'O estilo masculino também tem muita versatilidade!'),
    (49, 'Qual peça você acha que é um investimento de moda?'),
    (50, 'Look streetwear para quem curte estilo urbano!'),
    (51, 'Já usou chapéu como acessório? Super estiloso!'),
    (52, 'Moda e conforto podem andar juntos sim!'),
    (53, 'Qual a peça que você sempre repete no dia a dia?'),
    (54, 'Invista em roupas que fazem você se sentir confiante!'),
    (55, 'O que acha de peças feitas com tecidos tecnológicos?'),
    (56, 'Já pensou em montar um guarda-roupa cápsula?'),
    (57, 'Looks coloridos para dar energia no seu dia!'),
    (58, 'Você prefere looks mais formais ou despojados?'),
    (59, 'Como combinar sapatos com a roupa? Dica rápida!'),
    (60, 'Roupas de inverno que além de quentinhas são estilosas!'),
    (61, 'Qual seu estilo favorito de jaqueta?'),
    (62, 'Os acessórios certos transformam qualquer look!'),
    (63, 'Já experimentou usar roupas com estampa animal?'),
    (64, 'Qual seu look ideal para um encontro?'),
    (65, 'Dica: roupas de cores neutras combinam com tudo!'),
    (66, 'Você prefere roupas feitas à mão ou industrializadas?'),
    (67, 'Como escolher o melhor jeans para seu corpo?'),
    (68, 'Moda sustentável: pequenas atitudes, grande impacto!'),
    (69, 'Já fez customização DIY nas suas roupas?'),
    (70, 'Qual peça vintage você gostaria de ter?'),
    (71, 'Look para o verão: frescor e estilo na medida!'),
    (72, 'Você prefere estampas florais ou geométricas?'),
    (73, 'Sapatos confortáveis para usar o dia todo!'),
    (74, 'Aposte em acessórios que refletem sua personalidade!'),
    (75, 'Qual peça é seu verdadeiro “curinga”?'),
    (76, 'Você gosta de moda minimalista?'),
    (77, 'Como escolher um bom blazer para ocasiões formais?'),
    (78, 'Qual é a peça que você gostaria de reinventar?')
    (79, 'Dicas para combinar estampas sem errar!'),
    (80, 'Qual sua opinião sobre fast fashion?'),
    (81, 'Você tem um look favorito para sair com amigos?'),
    (82, 'Já usou alguma peça inspirada em outra cultura?'),
    (83, 'Looks para dias chuvosos com estilo!'),
    (84, 'Você prefere bolsas grandes ou pequenas?'),
    (85, 'Qual seu acessório indispensável para o inverno?'),
    (86, 'Como usar roupas oversize sem perder o estilo?'),
>>>>>>> 463b200ccabf9a7956238e8c617833ef4b5c1858
    (87, 'Roupas feitas por designers independentes têm personalidade! 👗'),
    (88, 'Qual seu estilo preferido para o trabalho? 💼'),
    (89, 'Você gosta de usar chapéus ou bonés? 🎩🧢'),
    (90, 'Dica rápida: misture tecidos para um look diferenciado! 🧵'),
    (91, 'Como a moda pode ajudar na autoestima? 💖'),
    (92, 'Qual seu look preferido para festas? 🎉'),
    (93, 'Já experimentou usar roupas com brilho? ✨'),
    (94, 'A moda é uma arte que você veste todo dia! 🎨'),
    (95, 'Qual peça você nunca deixaria de lado? 🧥'),
    (96, 'Já fez alguma troca de roupas com amigas? ♻️'),
    (97, 'Como cuidar das suas roupas para durarem mais? 🧺'),
    (98, 'Você prefere looks mais clássicos ou alternativos? 🎩'),
    (99, 'Qual seu sapato favorito para eventos formais? 👠'),
    (100, 'A moda é sua melhor forma de se expressar! Seja autêntico(a)! 🌟');



-- Create a table for notifications


CREATE TABLE notifications (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE,
    chat_id INTEGER REFERENCES chats(id) ON DELETE CASCADE, 
    message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- Insert sample data into notifications table
INSERT INTO notifications (user_id, post_id, chat_id, message) VALUES
(1, 1, 1, 'Você foi marcado em uma nova publicação.'),
(2, 2, 2, 'Alguém comentou no seu post! Confira agora.'),
(3, 3, 3, 'Chegou um novo comentário para você.'),
(4, 4, 4, 'Um novo comentário surgiu na sua timeline.'),
(5, 5, 5,  'Um usuário curtiu sua última postagem.');
(6, 6, 6, 'Você foi mencionado em uma conversa.'),
(7, 7, 7, 'Notificação: novo comentário recebido.'),
(8, 8, 8, 'O seu conteúdo está ganhando atenção! Veja quem interagiu.'),
(9, 9, 9, 'Alerta de interação: seu post recebeu uma curtida.'),
(10, 10, 10, 'Sua postagem acabou de ser curtida!'),
(11, 11, 11, 'Seu conteúdo chamou atenção! Novo comentário.'),
(12, 12, 12, 'Você foi marcado em uma nova publicação.'),
(13, 13, 13, 'Mais uma curtida no seu post. As pessoas estão adorando!'),
(14, 14, 14, 'Seu comentário foi respondido!'),
(15, 15, 15, 'Curtiram seu post! Vá conferir!'),
(16, 16, 'Curtiram seu post! Vá conferir!'),
(17, 17, 'Você foi marcado em uma nova publicação.'),
(18, 18, 'Tem novidade no seu post. Alguém interagiu!'),
(19, 19, 'Mais uma curtida no seu post. As pessoas estão adorando!'),
(20, 20, 'Você foi marcado em uma nova publicação.'),
(21, 21, 'Você recebeu uma nova curtida agora mesmo.'),
(22, 22, 'Nova interação no seu conteúdo! Veja quem comentou.'),
(23, 23, 'Nova curtida recebida. Continue postando!'),
(24, 24, 'Parabéns! Você recebeu uma nova curtida.'),
(25, 25, 'Nova interação no seu conteúdo! Veja quem comentou.'),
(26, 26, 'Um usuário curtiu sua última postagem.'),
(27, 27, 'Curtida recebida! Alguém gostou da sua postagem.'),
(28, 28, 'Notificação: novo comentário recebido.'),
(29, 29, 'Chegou um novo comentário para você.'),
(30, 30, 'Você foi mencionado em um comentário.');

INSERT INTO notifications (user_id, post_id, message, lida, enviada) VALUES
(31, 31, 'Você ganhou uma curtida extra! Veja quem foi.'),
(32, 32, 'Alguém comentou no seu post! Confira agora.'),
(33, 33, 'Novo comentário detectado. Confira agora.'),
(34, 34, 'Notificação: novo comentário recebido.'),
(35, 35, 'Tem novidade no seu post. Alguém interagiu!'),
(36, 36, 'Seu conteúdo chamou atenção! Novo comentário.'),
(37, 37, 'Você foi mencionado em uma conversa.'),
(38, 38, 'Curtiram seu post! Vá conferir!'),
(39, 39, 'Parabéns! Você recebeu uma nova curtida.'),
(40, 40, 'Chegou um novo comentário para você.'),
(41, 41, 'Um novo comentário surgiu na sua timeline.'),
(42, 42, 'Seu post recebeu uma nova interação.'),
(43, 43, 'Curtida recebida! Alguém gostou da sua postagem.'),
(44, 44, 'Você foi marcado em uma nova publicação.'),
(45, 45, 'Alerta de interação: seu post recebeu uma curtida.'),
(46, 46, 'Novo comentário na sua postagem!'),
(47, 47, 'Alguém comentou no seu post! Confira agora.'),
(48, 48, 'Você foi mencionado em um comentário.'),
(49, 49, 'Tem uma nova curtida esperando por você!'),
(50, 50, 'Mais uma curtida no seu post. As pessoas estão adorando!'),
(51, 51, 'Nova curtida recebida. Continue postando!'),
(52, 52, 'Seu conteúdo chamou atenção! Novo comentário.'),
(53, 53, 'O seu conteúdo está ganhando atenção! Veja quem interagiu.'),
(54, 54, 'Seu post recebeu uma nova interação.'),
(55, 55, 'Você foi marcado em uma nova publicação.'),
(56, 56, 'Notificação: novo comentário recebido.'),
(57, 57, 'Você ganhou uma curtida extra! Veja quem foi.'),
(58, 58, 'Alguém comentou no seu post! Confira agora.'),
(59, 59, 'Você foi mencionado em uma conversa.'),
(60, 60, 'Curtiram seu post! Vá conferir!');


INSERT INTO notifications (user_id, post_id, message, lida, enviada) VALUES
(61, 61, 'Parabéns! Você recebeu uma nova curtida.'),
(62, 62, 'Tem novidade no seu post. Alguém interagiu!'),
(63, 63, 'Novo comentário na sua postagem!'),
(64, 64, 'Curtiram seu post! Vá conferir!'),
(65, 65, 'Você foi mencionado em um comentário.'),
(66, 66, 'Chegou um novo comentário para você.'),
(67, 67, 'Seu post recebeu uma nova interação.'),
(68, 68, 'Você foi mencionado em uma conversa.'),
(69, 69, 'Nova curtida recebida. Continue postando!'),
(70, 70, 'Você foi marcado em uma nova publicação.'),
(71, 71, 'Mais uma curtida no seu post. As pessoas estão adorando!'),
(72, 72, 'Seu comentário foi respondido!'),
(73, 73, 'Novo comentário detectado. Confira agora.'),
(74, 74, 'Alguém comentou no seu post! Confira agora.'),
(75, 75, 'Alerta de interação: seu post recebeu uma curtida.'),
(76, 76, 'Tem uma nova curtida esperando por você!'),
(77, 77, 'Você recebeu uma nova curtida agora mesmo.'),
(78, 78, 'Notificação: novo comentário recebido.'),
(79, 79, 'Curtida recebida! Alguém gostou da sua postagem.'),
(80, 80, 'Seu conteúdo chamou atenção! Novo comentário.'),
(81, 81, 'Você ganhou uma curtida extra! Veja quem foi.'),
(82, 82, 'Curtiram seu post! Vá conferir!'),
(83, 83, 'Chegou um novo comentário para você.'),
(84, 84, 'Novo comentário na sua postagem!'),
(85, 85, 'Você foi mencionado em um comentário.'),
(86, 86, 'Tem novidade no seu post. Alguém interagiu!'),
(87, 87, 'Parabéns! Você recebeu uma nova curtida.'),
(88, 88, 'Nova curtida recebida. Continue postando!'),
(89, 89, 'Seu post recebeu uma nova interação.'),
(90, 90, 'Você foi marcado em uma nova publicação.');

INSERT INTO notifications (user_id, post_id, message, lida, enviada) VALUES
(91, 91, 'O seu conteúdo está ganhando atenção! Veja quem interagiu.'),
(92, 92, 'Curtiram seu post! Vá conferir!'),
(93, 93, 'Alguém comentou no seu post! Confira agora.'),
(94, 94, 'Você foi mencionado em um comentário.'),
(95, 95, 'Notificação: novo comentário recebido.'),
(96, 96, 'Você ganhou uma curtida extra! Veja quem foi.'),
(97, 97, 'Seu comentário foi respondido!'),
(98, 98, 'Novo comentário detectado. Confira agora.'),
(99, 99, 'Curtida recebida! Alguém gostou da sua postagem.'),
(100, 100, 'Parabéns! Você recebeu uma nova curtida.'),
(1, 101, 'Chegou um novo comentário para você.'),
(2, 102, 'Tem novidade no seu post. Alguém interagiu!'),
(3, 103, 'Alerta de interação: seu post recebeu uma curtida.'),
(4, 104, 'Seu conteúdo chamou atenção! Novo comentário.'),
(5, 105, 'Você foi marcado em uma nova publicação.'),
(6, 106, 'Mais uma curtida no seu post. As pessoas estão adorando!'),
(7, 107, 'Nova curtida recebida. Continue postando!'),
(8, 108, 'Você recebeu uma nova curtida agora mesmo.'),
(9, 109, 'Você foi mencionado em uma conversa.'),
(11, 110, 'Seu post recebeu uma nova interação.'),
(11, 111, 'Tem uma nova curtida esperando por você!'),
(12, 112, 'Notificação: novo comentário recebido.'),
(13, 113, 'Seu comentário foi respondido!'),
(14, 114, 'O seu conteúdo está ganhando atenção! Veja quem interagiu.'),
(15, 115, 'Você foi mencionado em uma conversa.'),
(16, 116, 'Tem novidade no seu post. Alguém interagiu!'),
(17, 117, 'Novo comentário na sua postagem!'),
(18, 118, 'Curtida recebida! Alguém gostou da sua postagem.'),
(19, 119, 'Alguém comentou no seu post! Confira agora.'),
(20, 120, 'Curtiram seu post! Vá conferir!');


INSERT INTO notifications (user_id, post_id, message, lida, enviada) VALUES
(21, 121, 'Você ganhou uma curtida extra! Veja quem foi.'),
(22, 122, 'Tem uma nova curtida esperando por você!'),
(23, 123, 'Novo comentário detectado. Confira agora.'),
(24, 124, 'Seu conteúdo chamou atenção! Novo comentário.'),
(25, 125, 'Você foi marcado em uma nova publicação.'),
(26, 126, 'Chegou um novo comentário para você.'),
(27, 127, 'Mais uma curtida no seu post. As pessoas estão adorando!'),
(28, 128, 'Seu comentário foi respondido!'),
(29, 129, 'Alerta de interação: seu post recebeu uma curtida.'),
(30, 130, 'Você foi mencionado em um comentário.'),
(31, 131, 'Você recebeu uma nova curtida agora mesmo.'),
(32, 132, 'Seu post recebeu uma nova interação.'),
(33, 133, 'Tem novidade no seu post. Alguém interagiu!'),
(34, 134, 'Curtiram seu post! Vá conferir!'),
(35, 135, 'Notificação: novo comentário recebido.'),
(36, 136, 'O seu conteúdo está ganhando atenção! Veja quem interagiu.'),
(37, 137, 'Nova curtida recebida. Continue postando!'),
(38, 138, 'Parabéns! Você recebeu uma nova curtida.'),
(39, 139, 'Você foi mencionado em uma conversa.'),
(40, 140, 'Curtida recebida! Alguém gostou da sua postagem.'),
(41, 141, 'Você foi marcado em uma nova publicação.'),
(42, 142, 'Tem uma nova curtida esperando por você!'),
(43, 143, 'Seu conteúdo chamou atenção! Novo comentário.'),
(44, 144, 'Novo comentário na sua postagem!'),
(45, 145, 'Alguém comentou no seu post! Confira agora.'),
(46, 146, 'Você foi mencionado em um comentário.'),
(47, 147, 'Seu post recebeu uma nova interação.'),
(48, 148, 'Você ganhou uma curtida extra! Veja quem foi.'),
(49, 149, 'Nova curtida recebida. Continue postando!'),
(50, 150, 'Mais uma curtida no seu post. As pessoas estão adorando!');

INSERT INTO notifications (user_id, post_id, message, lida, enviada) VALUES
(51, 151, 'Seu post recebeu uma nova reação!'),
(52, 152, 'Alguém acabou de interagir com sua publicação!'),
(53, 153, 'Você tem uma nova atividade no seu post!'),
(54, 154, 'Seu conteúdo chamou atenção novamente!'),
(55, 155, 'Novo feedback chegou para o seu post!'),
(56, 156, 'Alguém curtiu seu comentário!'),
(57, 157, 'Você foi citado em uma nova interação!'),
(58, 158, 'Recebemos uma nova curtida para você!'),
(59, 159, 'Alguém achou seu post incrível!'),
(60, 160, 'Nova curtida no ar! Confira seu post.'),
(61, 161, 'Seu conteúdo acabou de receber mais amor!'),
(62, 162, 'Alerta: seu post está ganhando destaque!'),
(63, 163, 'Alguém engajou com sua publicação agora mesmo!'),
(64, 164, 'Uma pessoa acabou de comentar no seu post.'),
(65, 165, 'Seu post inspirou alguém a comentar!'),
(66, 166, 'Você foi mencionado em uma discussão.'),
(67, 167, 'Comentário novo à vista no seu conteúdo!'),
(68, 168, 'Você tem uma interação novinha em folha.'),
(69, 169, 'Seu conteúdo voltou a ser comentado.'),
(70, 170, 'Sua postagem está rendendo boas reações!'),
(71, 171, 'Mensagem nova no seu post!'),
(72, 172, 'Alguém reagiu ao que você postou.'),
(73, 173, 'Sua publicação continua gerando impacto.'),
(74, 174, 'Mais uma curtida para a conta!'),
(75, 175, 'Um novo comentário chegou até você!'),
(76, 176, 'Seu post tocou alguém — veja o novo comentário.'),
(77, 177, 'Interação recente no seu conteúdo!'),
(78, 178, 'Sua publicação está brilhando!'),
(79, 179, 'Atividade recente detectada no seu post.'),
(80, 180, 'O seu conteúdo foi marcado com uma reação.'),
(81, 181, 'Seu post continua movimentando a timeline.'),
(82, 182, 'Opa! Novo engajamento na área!'),
(83, 183, 'Mais alguém chegou até sua publicação.'),
(84, 184, 'Chegou uma nova notificação de atividade!'),
(85, 185, 'Sua opinião gerou uma resposta.'),
(86, 186, 'Uma nova curtida chegou para seu conteúdo.'),
(87, 187, 'A galera está falando do seu post.'),
(88, 188, 'Seu conteúdo foi descoberto por mais alguém!'),
(89, 189, 'Reagiram à sua última postagem.'),
(90, 190, 'Estão comentando sobre o que você disse!'),
(91, 191, 'Nova atividade envolvendo você.'),
(92, 192, 'Estão falando do seu post!'),
(93, 193, 'Alguém acabou de interagir com sua ideia!'),
(94, 194, 'Chegou uma reação especial para você.'),
(95, 195, 'Um toque mágico no seu post: nova curtida!'),
(96, 196, 'Sua publicação brilhou de novo!'),
(97, 197, 'Novo envolvimento no seu conteúdo!'),
(98, 198, 'Você atraiu mais uma curtida.'),
(19, 199, 'Seu post ainda está gerando impacto.'),
(20, 200, 'Uma nova notificação brilhante chegou até você.');




-- Create a table for comments

CREATE TABLE comments (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE,
    text_comment VARCHAR(350),
    date_comment TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert sample data into comments table

INSERT INTO comments (user_id, post_id, text_comment) 
VALUES 
    (1, 1, 'Roupas de inverno são as melhores!'),
    (2, 1, 'Amo o inverno'),
    (3, 2, 'Roupas de verão são as melhores!'),
    (4, 2, 'Amo o verão'),
    (5, 3, 'Roupas de outono são as melhores!'),
    (6, 3, 'Amo o outono'),
    (7, 4, 'Roupas de primavera são as melhores!'),
    (8, 4, 'Amo a primavera'),
    (9, 5, 'Muito boa essa combinação para festa'),
    (1, 5, 'Roupas de praia são muito divas'),
    (2, 6, 'Simplesmente impecável! Esse look tá um arraso'),
    (3, 6, 'O estilo tá em outro nível! Amei demais'),
    (7, 7, 'Você sempre entrega tudo no visual!'),
    (4, 7, 'Chique, moderno e cheio de atitude. Amei!'),
    (5, 8, 'Essa combinação ficou perfeita em você!'),
    (6, 8, 'Arrasou demais! Você é uma verdadeira fashionista!'),
    (7, 9, 'Essa jaqueta é tudo! Onde você comprou?'),
    (8, 9, 'Amei o mix de texturas, super tendência!'),
    (9, 10, 'Esse look é puro glamour! Você arrasa sempre!'),
    (1, 10, 'Amei a combinação de cores! Super estiloso!'),
    (2, 11, 'Esse vestido é um sonho! Onde você encontrou?'),
    (3, 11, 'Você tá linda demais! Amei o look!'),
    (4, 12, 'Essa blusa é tudo! Você arrasa no estilo!'),
    (5, 12, 'Amei a estampa! Super fashionista!'),
    (6, 13, 'Esse look tá perfeito pra festa! Arrasou!'),
    (7, 13, 'Você sempre entrega tudo no visual!'),
    (8, 14, 'Essa combinação ficou perfeita em você!'),
    (9, 14, 'Arrasou demais! Você é uma verdadeira fashionista!'),
    (10, 15, 'Essa paleta de cores tá perfeita pro outono'),
    (1, 15, 'Look comfy e estiloso ao mesmo tempo'),
    (2, 16, 'A bota deu um toque poderoso no visual'),
    (3, 16, 'Dá aula de estilo todo dia, né?'),
    (4, 17, 'Pinterest deveria te contratar urgente!'),
    (22, 17, 'Se estilo fosse crime, você já estaria presa'),
    (5, 18, 'Metade fashion week, metade sonho'),
    (12, 18, 'Qual a inspiração desse look? Amei demais!'),
    (13, 19, 'Me ajuda a montar algo parecido? Tô sem ideias'),
    (12, 19, 'Você acha que esse look combina com tênis branco também?'),
    (13, 20, 'Usaria fácil esse look! Tem link das peças?'),
    (14, 20, 'Você é a definição de estilo'),
    (15, 21, 'Cada look melhor que o outro, como pode?'),
    (2, 21, 'Você transforma qualquer roupa em tendência'),
    (2, 22, 'A energia desse visual tá surreal'),
    (3, 22, 'Look de milhões'),
    (23, 23, 'Essa calça é TUDO! Onde encontro uma igual?'),
    (12, 23, 'Amei como o blazer deu um ar sofisticado'),
    (12, 24, 'O vestido tá a coisa mais linda, super delicado'),
    (1, 24, 'Esse conjunto tá super na moda, amei a vibe!'),
    (2, 25, 'Tênis branco e vestido? Combinação perfeita!'),
    (3, 25, 'Esse look tem a sua cara! Cheio de atitude'),
    (25, 26, 'Você tem um estilo único, dá pra ver de longe'),
    (26, 26, 'Zero defeitos! Tudo combinando perfeitamente'),
    (27, 27, 'Dá pra ver que você entende MUITO de moda'),
    (28, 27, 'Inspirador! Já quero copiar esse estilo'),
    (29, 28, 'Tô te denunciando por excesso de beleza e estilo'),
    (30, 28, 'Me ensina a ser estilosa assim, por favor'),
    (31, 29, 'Nem o espelho aguenta tanta beleza'),
    (32, 29, 'Você é o próprio moodboard do Pinterest'),
    (33, 30, 'A moda agradece sua existência'),
    (34, 30, 'Look incrível! Você monta sozinha ou tem stylist?'),
    (35, 31, 'Qual app você usa pra editar as fotos? Ficaram lindas!'),
    (36, 31, 'Esse look daria super certo numa sessão de fotos profissional!'),
    (37, 32, 'Daria certo com acessórios dourados também, né?'),
    (38, 32, 'Qual a sua maior inspiração de moda hoje em dia?'),
    (39, 33, 'A cara do verão! Look leve e cheio de estilo'),
    (40, 33, 'Esse biquíni tá tudo! A cor valorizou muito você'),
    (41, 34, 'Praia + estilo = você arrasando como sempre'),
    (42, 34, 'Diva solar! Iluminando o feed com esse look'),
    (43, 35, 'Chapéu, óculos, biquíni… entregou tudo!'),
    (44, 35, 'Look quentinho e estiloso, a combinação perfeita'),
    (45, 36, 'Frio com personalidade, amei esse casaco demais!'),
    (46, 36, 'Essa sobreposição ficou INCRÍVEL'),
    (47, 37, 'Look inverno digno de passarela!'),
    (48, 37, 'Mostrando que no frio a gente também lacra'),
    (49, 38, 'Pronta pra brilhar a noite toda!'),
    (50, 38, 'Look poderoso! Essa produção tá de tirar o fôlego'),
    (51, 39, 'A rainha da balada chegou, e chegou linda'),
    (52, 39, 'Muito brilho, muita atitude. Simplesmente perfeita'),
    (53, 40, 'Esse vestido tá digno de tapete vermelho'),
    (54, 40, 'Simples, leve e mega estilosa! Amei a vibe'),
    (55, 41, 'Look comfy que não perde o charme'),
    (56, 41, 'Dá vontade de usar esse look todo dia!'),
    (57, 41, 'Casual sim, sem graça nunca'),
    (58, 42, 'Look do dia aprovado com louvor'),
    (58, 42, 'Esse look tá MUITO street, amei demais!'),
    (59, 43, 'Estilo urbano que é puro impacto'),
    (60, 43, 'Você é a definição de street style'),
    (61, 44, 'Combinação de cores impecável, tá demais!'),
    (62, 44, 'Look street com atitude de sobra'),
    (63, 45, 'Pura sofisticação! Look digno de revista'),
    (64, 45, 'O clássico nunca sai de moda – e você sabe usar como ninguém'),
    (65, 46, 'A elegância mora nos detalhes, e você arrasou!'),
    (66, 46, 'Esse look respira classe e estilo'),
    (67, 47, 'Visual impecável e atemporal'),
    (1, 47, 'Que combinação de cores incrível! Esse look ficou super harmônico'),
    (1, 48, 'Você tem um talento único pra montar visuais estilosos e modernos'),
    (2, 48, 'Amei o contraste das peças, deu um ar super autêntico ao look'),
    (2, 49, 'Look super bem pensado, confortável e cheio de personalidade'),
    (3, 49, 'Você sempre acerta nos detalhes. Esse visual tá impecável'),
    (4, 50, 'Cada peça parece ter sido feita sob medida pra você, incrível!'),
    (5, 50, 'A escolha dos acessórios deu um toque final maravilhoso'),
    (6, 51, 'Dá pra ver que você entende de moda só pelo bom gosto'),
    (7, 51, 'Um dos melhores looks que vi hoje no feed, sério mesmo'),
    (8, 52, 'Essa paleta de cores é a cara da estação! Amei demais'),
    (9, 52, 'Que produção linda! Elegante e moderna na medida certa'),
    (10, 53, 'Look super versátil, usaria fácil em várias ocasiões'),
    (11, 53, 'O equilíbrio entre casual e chic ficou perfeito!'),
    (12, 54, 'Tá parecendo capa de revista de moda! Arrasou demais'),
    (13, 54, 'O look tá tão bom que nem sei o que elogiar primeiro'),
    (14, 55, 'Esse outfit transmite confiança e estilo'),
    (15, 55, 'A energia desse look tá surreal, me inspirou real'),
    (16, 56, 'Look fresh, leve e super atual. Amei a vibe'),
    (17, 56, 'Que styling perfeito! Essa composição merece destaque'),
    (18, 57, 'Você consegue transformar qualquer look simples em algo incrível'),
    (19, 57, 'Seu estilo tem identidade e isso é raro de ver!'),
    (20, 58, 'Que bom gosto! Cada detalhe conversa com o outro'),
    (21, 58, 'Fashion, ousada e autêntica. Amei o look inteiro'),
    (22, 59, 'Look comfy com pegada fashionista? Você entrega tudo'),
    (23, 59, 'Tá lindíssima! Esse visual te valorizou demais'),
    (24, 60, 'Já favoritei pra usar como referência no próximo look'),
    (25, 60, 'Inspiração real de moda no feed hoje'),
    (26, 61, 'Essa jaqueta é o auge! Onde você achou essa lindeza?'),
    (27, 61, 'Com esse estilo você comanda qualquer ambiente'),
    (28, 62, 'Dá aula de elegância e autenticidade em cada post'),
    (29, 62, 'Seu visual fala por si: cheio de atitude e bom gosto'),
    (30, 63, 'A produção tá perfeita! Super profissional e estilosa'),
    (31, 63, 'Que vibe maravilhosa! Transmite leveza e segurança'),
    (32, 64, 'Roubei essa ideia pro meu próximo look, tá incrível'),
    (33, 64, 'Look digno de fashion week! Você arrasou demais'),
    (34, 65, 'Amo como você combina peças básicas com personalidade'),
    (35, 65, 'Tá muito fashion, parece saída direto de editorial'),
    (36, 66, 'Um visual criativo, moderno e super bem executado'),
    (37, 66, 'Cores, textura, corte… tudo no ponto certo!'),
    (38, 67, 'Visual bem construído e cheio de presença!'),
    (39, 67, 'Essa composição ficou muito além do básico! Você brilhou'),
    (40, 68, 'Look com presença! Amei o impacto da produção'),
    (41, 68, 'Cada post seu é um banho de inspiração fashion'),
    (42, 69, 'Que arraso! Mostrando que moda é expressão'),
    (43, 69, 'Look super atual e com uma pegada descolada'),
    (44, 70, 'Você dominou a estética urbana com muita elegância'),
    (45, 70, 'Ousada na medida certa! Esse look tá incrível'),
    (46, 71, 'Super bem equilibrado, confortável e fashion'),
    (47, 71, 'A silhueta do look ficou linda demais em você'),
    (48, 72, 'Você realmente sabe como valorizar cada peça'),
    (49, 72, 'Simplesmente apaixonado(a) nesse look! Você tem um estilo único'),
    (50, 73, 'O outfit ficou sofisticado sem perder a essência urbana'),
    (51, 73, 'Consegue ser moderna, elegante e ousada no mesmo look!'),
    (52, 74, 'Essa composição tá tão equilibrada que virou minha nova inspiração'),
    (53, 74, 'Cada peça foi escolhida com tanta precisão, tô impressionado(a)'),
    (54, 75, 'Você faz da moda uma arte! Cada post é um quadro'),
    (55, 75, 'Visual perfeito da cabeça aos pés!'),
    (56, 76, 'Simples, direto e cheio de atitude. Amei o conceito'),
    (57, 76, 'Essa produção tá a cara do streetwear chique!'),
    (58, 77, 'Nunca decepciona no estilo! Já virou referência'),
    (59, 77, 'O equilíbrio entre ousadia e sofisticação tá surreal!'),
    (60, 78, 'Um mix de tendências com identidade, amei demais!'),
    (61, 78, 'Como consegue sempre inovar e surpreender no visual?'),
    (62, 79, 'Até o cenário combina com o look! Tudo muito bem pensado'),
    (63, 79, 'Cada foto sua vira inspiração pro meu próprio estilo'),
    (64, 80, 'Você mostra que estilo é uma forma de expressão'),
    (65, 80, 'O caimento dessa roupa ficou perfeito em você!'),
    (66, 81, 'Que presença! Você domina o look e o ambiente'),
    (67, 81, 'Super fashionista sem parecer forçado. Isso é talento'),
    (68, 82, 'Essa produção me ganhou no primeiro olhar'),
    (69, 82, 'Look conceito e execução perfeita'),
    (70, 83, 'Ouse mais! O resultado fica incrível em você'),
    (71, 83, 'As combinações que você faz são sempre surpreendentes'),
    (72, 84, 'Dá vontade de copiar esse look agora mesmo!'),
    (73, 84, 'Acessórios incríveis! Deram vida ao visual'),
    (74, 85, 'A vibe dessa foto com esse look ficou TUDO'),
    (75, 85, 'É sobre ter estilo e saber usar, e você sabe!'),
    (76, 86, 'Visual criativo, moderno e com alma'),
    (77, 86, 'Tudo tão bem encaixado, parece editorial de moda'),
    (78, 87, 'Você inspira com cada detalhe desse visual'),
    (79, 87, 'A combinação de tecidos ficou perfeita!'),
    (80, 88, 'Totalmente fashion sem perder o conforto. Isso sim!'),
    (81, 88, 'O jogo de cores ficou sensacional! Super original'),
    (82, 89, 'Eu só queria metade desse bom gosto kkkkk'),
    (83, 89, 'Esse visual tem um quê de ousadia elegante'),
    (84, 90, 'O look tá tão bom que eu salvei aqui como referência'),
    (85, 90, 'Um arraso do início ao fim. Amei a composição'),
    (86, 91, 'Look simples com presença de sobra!'),
    (87, 91, 'Essa é a definição de estar bem vestida'),
    (88, 92, 'As camadas desse look ficaram incríveis. Super estilosa!'),
    (89, 92, 'Você entrega conteúdo de moda com alma'),
    (90, 93, 'Gosto tanto desse estilo que já virou meu preferido!'),
    (91, 93, 'Essa produção tá gritando “confiança”! Adorei'),
    (92, 94, 'O toque urbano nesse look fez toda a diferença'),
    (93, 94, 'Tá uma visão de tão linda com esse visual'),
    (94, 95, 'Essa harmonia entre peças e acessórios ficou perfeita'),
    (95, 95, 'O look é top, mas sua atitude é o que dá o brilho final'),
    (96, 96, 'Achei tudo muito bem coordenado. Parabéns pelo bom gosto!'),
    (97, 96, 'Um visual cheio de força, personalidade e elegância'),
    (98, 97, 'Você tem o poder de transformar qualquer look básico em algo extraordinário'),
    (99, 97, 'Esse look exala autenticidade, não tem como não notar!'),
    (1, 98, 'A vibe desse visual tá muito Pinterest'),
    (2, 98, 'Toda fashionista deveria ver esse post, sério!'),
    (3, 99, 'Que harmonia! Estilo e presença num mesmo clique'),
    (4, 99, 'Cada detalhe dessa composição mostra sua identidade');


INSERT INTO comments (user_id, post_id, text_comment) 
VALUES 
    (5, 100, 'Seu senso de estilo é realmente único, parabéns!'),
    (6, 100, 'Essa peça central é maravilhosa! Super tendência'),
    (7, 101, 'Look comfy com toque fashion? Isso é tudo!'),
    (8, 101, 'Você não segue tendências, você cria!'),
    (9, 102, 'Me ensina a montar um visual assim? Perfeita demais'),
    (10, 102, 'Estilo e autoestima andam juntos aqui!'),
    (11, 103, 'Uma explosão de estilo, criatividade e confiança'), 
    (12, 103, 'Nunca vi uma combinação tão bem pensada quanto essa!'),
    (13, 104, 'Isso sim é saber se vestir com atitude'),
    (14, 104, 'Cada detalhe desse visual tá gritando personalidade!'),
    (15, 105, 'A pegada minimalista deixou tudo ainda mais elegante'),
    (16, 105, 'Que produção estilosa! Dá até vontade de montar um igual'),
    (17, 106, 'Esse blazer com jeans ficou incrível demais!'),
    (18, 106, 'Esse equilíbrio entre peças largas e justas ficou ótimo'),
    (19, 107, 'Você arrasou no look e na pose! Tudo perfeito'),
    (20, 107, 'Um toque de ousadia nunca é demais e você provou isso!'),
    (21, 108, 'Esse visual ficou harmônico da cabeça aos pés'),
    (22, 108, 'Tá com cara de capa de revista! Linda demais'),
    (23, 109, 'Sua identidade sempre aparece nos seus looks, e isso é incrível'),
    (24, 109, 'Esse look tá tão alinhado com sua vibe, amei!'),
    (25, 110, 'Tá um arraso do cabelo ao sapato!'),
    (26, 110, 'Visual equilibrado, bonito e cheio de estilo'),
    (27, 111, 'Essa produção tem impacto, elegância e muita personalidade'),
    (28, 111, 'Look prático, estiloso e super atual!'),
    (29, 112, 'Sabe quando tudo dá certo? Foi o caso desse look'),
    (30, 112, 'Você carrega o look com tanta confiança! Isso é lindo de ver'),
    (31, 113, 'Amei a mistura de peças clássicas com toques modernos'),
    (32, 113, 'Esse visual tá vibrante, estiloso e super inspirador'),
    (33, 114, 'Dá pra ver que foi tudo feito com muito cuidado e estilo'),
    (34, 114, 'Esse fundo combinou demais com o look, tudo perfeito!'),
    (35, 115, 'Parece uma produção de cinema de tão bem feita'),
    (36, 115, 'Esse outfit me deixou apaixonado(a), sério!'),
    (37, 116, 'Você tá servindo moda com personalidade em cada post'),
    (38, 116, 'Look do dia? Mais parece look do ano!'),
    (39, 117, 'Essa vibe tá maravilhosa, quero copiar tudo!'),
    (40, 117, 'Um estilo que equilibra conforto e elegância com perfeição'),
    (77, 118, 'Look comfy e fashion ao mesmo tempo'),
    (78, 118, 'Essa composição ficou chiquérrima!'),
    (79, 119, 'Cada detalhe desse visual está impecável!'),
    (80, 119, 'Simplicidade com toque de sofisticação'),
    (81, 120, 'O street style nunca esteve tão em alta!'),
    (82, 120, 'Mix de estampas que funcionou perfeitamente'),
    (83, 121, 'Cores vibrantes que contagiam!'),
    (84, 121, 'Visual urbano com identidade!'),
    (85, 122, 'Trendy, atual e super estilosa!'),
    (86, 122, 'Esse look poderia estar em uma revista de moda!'),
    (87, 123, 'Inspiração pura! Cada dia um desfile diferente'),
    (88, 123, 'Look comfy e autêntico, adorei!'),
    (89, 124, 'Totalmente fashion week vibes!'),
    (90, 124, 'Estilo fresh e moderno!'),
    (91, 125, 'Combinação ousada e perfeita'),
    (92, 125, 'Seu guarda-roupa deve ser um sonho!'),
    (93, 126, 'Look minimalista cheio de personalidade!'),
    (94, 126, 'Acessórios on point!'),
    (95, 127, 'Amei o contraste desse look!'),
    (96, 127, 'Look com toque artístico e fashion'),
    (97, 128, 'Elegância natural, sem esforço'),
    (98, 128, 'Look romântico e moderno ao mesmo tempo'),
    (99, 129, 'Essa bota é tudo! Arrasou demais'),
    (100, 129, 'Estilo urbano com alma fashionista'),
    (100, 130, 'Super criativa a combinação!'),
    (100, 130, 'Você transforma qualquer roupa em tendência!'),
    (100, 131, 'Estilo comfy chic ativado!'),
    (100, 131, 'Look poderoso e autêntico'),
    (100, 132, 'Ousadia com elegância, amei!'),
    (100, 132, 'Look tão leve quanto estiloso'),
    (100, 133, 'Chic & cool na medida certa'),
    (100, 133, 'Amando essa estética clean!'),
    (100, 134, 'Visual despojado com toque de luxo!'),
    (100, 134, 'Estilo que inspira! Continue assim'),
    (100, 135, 'Color blocking maravilhoso!'),
    (100, 135, 'Essa vibe fashion retrô tá incrível!'),
    (100, 136, 'Look que brilha sem esforço!'),
    (100, 136, 'Essa combinação tá um escândalo de linda!'),
    (100, 137, 'Mistura de texturas perfeita!'),
    (100, 137, 'Super fashionista com esse look all black'),
    (100, 138, 'Elegância moderna em cada detalhe'),
    (100, 138, 'Que arraso! O look grita atitude'),
    (100, 139, 'Você nasceu pra brilhar na moda'),
    (100, 139, 'Estilo próprio e marcante!'),
    (100, 140, 'Tudo nesse look combina contigo!'),
    (100, 140, 'Esse outfit é um verdadeiro statement!'),
    (100, 141, 'A energia desse look é única!'),
    (100, 141, 'Super criativa e ousada na escolha'),
    (100, 142, 'Look pra copiar já!'),
    (100, 142, 'Chique e descolada como sempre!'),
    (1, 143, 'Esse look é puro luxo!'),
    (2, 143, 'O equilíbrio entre conforto e estilo está perfeito'),
    (3, 144, 'Você domina a arte de se vestir bem'),
    (4, 144, 'Um visual que fala por si só!'),
    (5, 144, 'Moderno, autêntico e super fashion'),
    (6, 145, 'Ousadia e elegância no mesmo look!'),
    (7, 145, 'Essa vibe retrô tá incrível!'),
    (8, 145, 'Você consegue reinventar a moda todo dia'),
    (9, 146, 'Amei o toque de cor!'),
    (10, 146, 'Casual com muita personalidade'),
    (11, 146, 'Esse outfit tá gritando estilo!'),
    (12, 147, 'Que look icônico!'),
    (13, 147, 'Essa produção tá surreal de linda'),
    (14, 147, 'Looks assim me inspiram demais'),
    (15, 148, 'Acessórios on point, como sempre'),
    (16, 148, 'A harmonia desse look tá impecável'),
    (17, 148, 'Moda com alma, adorei demais!'),
    (18, 149, 'O street style ganhou outra cara com você'),
    (19, 149, 'Estilo refinado e super atual'),
    (20, 149, 'Simplesmente maravilhosa com esse visual');


    INSERT INTO comments (user_id, post_id, text_comment) 
VALUES 
    (21, 150, 'Essa composição tá perfeita dos pés à cabeça'),
    (22, 150, 'Um arraso de look, como sempre'),
    (23, 151, 'Esse toque monocromático ficou tudo!'),
    (24, 151, 'Sempre inovando com estilo'),
    (25, 152, 'Mistura de texturas que funcionou demais!'),
    (26, 152, 'Look inspirador e autêntico'),
    (27, 153, 'Que criatividade na escolha das peças!'),
    (28, 153, 'Estilo que transborda charme'),
    (29, 154, 'Totalmente apaixonada por esse visual'),
    (30, 154, 'Elegância e atitude em cada detalhe'),
    (31, 155, 'Super moderna e fashionista como sempre'),
    (32, 155, 'A vibe desse look tá sensacional'),
    (33, 156, 'Sempre entregando muito estilo'),
    (34, 156, 'Um look cheio de identidade'),
    (35, 157, 'O poder que esse outfit transmite'),
    (36, 157, 'Look comfy sem perder o glamour'),
    (37, 158, 'Esse conjunto tá perfeito demais'),
    (38, 158, 'Inspiração fashion do dia!'),
    (39, 159, 'Visual leve, lindo e cheio de charme'),
    (40, 159, 'A moda agradece por esse look'),
    (41, 160, 'Que look fresh e descolado'),
    (42, 160, 'Fashion sem esforço, amei!'),
    (43, 161, 'Tão estilosa que até o fundo combina contigo!'),
    (44, 161, 'Look digno de editorial de revista'),
    (45, 162, 'Essa jaqueta é simplesmente perfeita'),
    (46, 162, 'Tendência pura nesse visual'),
    (47, 163, 'Totalmente apaixonada pela escolha das cores'),
    (48, 163, 'Fashion em todos os ângulos'),
    (49, 164, 'Uma verdadeira obra de arte esse outfit'),
    (50, 164, 'Estilo que inspira e encanta'),
    (35, 165, 'Elegância natural e cheia de atitude'),
    (8, 165, 'Você domina a arte de se vestir bem'),
    (78, 166, 'Que look icônico!'),
    (69, 166, 'Sempre inovando com estilo'),
    (97, 167, 'Um look cheio de identidade'),
    (75, 167, 'Super moderna e fashionista como sempre'),
    (7, 168, 'Moda com alma, adorei demais!'),
    (80, 168, 'Super moderna e fashionista como sempre'),
    (19, 169, 'Um look cheio de identidade'),
    (54, 169, 'Acessórios on point, como sempre'),
    (3, 170, 'Esse look tá impecável!'),
    (45, 170, 'A paleta de cores ficou incrível'),
    (67, 171, 'Muito fashionista! Adorei demais'),
    (12, 171, 'Você entrega estilo em todos os detalhes'),
    (89, 172, 'Sensacional! A vibe tá tudo'),
    (33, 172, 'Elegância e ousadia em um só look'),
    (76, 173, 'Cada vez mais estilosa!'),
    (4, 173, 'Esse visual tá digno de capa de revista'),
    (98, 174, 'Look confortável e chique ao mesmo tempo!'),
    (50, 174, 'A composição tá perfeita, tô apaixonada'),
    (25, 175, 'Esse look tá falando alto!'),
    (7, 175, 'Você é pura inspiração de moda'),
    (63, 176, 'Estilo autêntico que inspira!'),
    (38, 176, 'Look moderno com um toque retrô, amei!'),
    (19, 177, 'Que combinação mais criativa!'),
    (85, 177, 'Muito conceito envolvido nesse outfit!'),
    (9, 178, 'Simplicidade e sofisticação num só post!'),
    (34, 178, 'Referência de estilo que fala, né?'),
    (91, 179, 'Você nunca erra no look, é surreal'),
    (27, 179, 'Vontade de copiar esse visual agora!'),
    (66, 180, 'Você sempre arrasa nas produções'),
    (80, 180, 'Essa energia fashion me pegou'),
    (22, 181, 'Acessórios no ponto certo!'),
    (58, 181, 'Esse look é tudo que eu precisava ver hoje'),
    (14, 182, 'Tem como ser mais fashionista? Amei!'),
    (99, 183, 'Visual fresh e sofisticado ao mesmo tempo'),
    (11, 183, 'Estilo que inspira! Tá linda demais'),
    (70, 184, 'Você entende de moda como ninguém'),
    (36, 184, 'Aquela produção que levanta o astral!'),
    (46, 185, 'Muito poder nesse look, mds'),
    (31, 185, 'Essa estética tá perfeita, sem defeitos'),
    (52, 186, 'Ousadia com muito bom gosto'),
    (18, 186, 'Tudo casando perfeitamente! Look 10/10'),
    (64, 187, 'Referência que fala, né?'),
    (73, 187, 'Tô encantada com esse visual'),
    (29, 188, 'Sempre um show de estilo por aqui'),
    (5, 188, 'Daria um quadro esse look!'),
    (81, 189, 'Composição leve e super estilosa'),
    (16, 189, 'Você é tendência ambulante!'),
    (92, 190, 'Detalhes que fazem toda a diferença'),
    (40, 190, 'Perfeição em forma de roupa'),
    (3, 191, 'Esse look fala por si só'),
    (87, 191, 'É sobre ser fashion e autêntica'),
    (20, 192, 'Tô viciada no seu estilo!'),
    (28, 192, 'Esse outfit tá tudo, sem defeitos'),
    (59, 193, 'Chique, moderna e criativa'),
    (95, 193, 'Fashion icon total'),
    (23, 194, 'Referência fashion da semana, com certeza!'),
    (15, 194, 'Tudo bem escolhido e combinado!'),
    (62, 195, 'Amando essa composição com tons neutros'),
    (90, 195, 'Você arrasa com pouco e com muito!'),
    (26, 196, 'Essa produção ficou muito charmosa'),
    (10, 196, 'Tem talento até pra montar looks'),
    (68, 197, 'Sofisticada na medida certa!'),
    (53, 197, 'Puro charme esse look todo trabalhado'),
    (37, 198, 'Esse look grita elegância!'),
    (93, 198, 'Mais um look que vai direto pra minha pasta de inspiração'),
    (2, 199, 'Estilo que combina com tua vibe'),
    (71, 199, 'Arrasou! A harmonia das peças ficou impecável'),
    (35, 200, 'Look urbano e cheio de atitude!'),
    (83, 200, 'Cada post é uma aula de moda');


-- Create a table for categories
CREATE TABLE categories (
    id SERIAL PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE
);

-- Insert sample data into categories table
INSERT INTO categories (name) VALUES
    ('Dress'),
    ('Hat'),
    ('Shoes'),
    ('Make Up'),
    ('Accessory');

