CREATE TABLE comments (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE,
    text_comment VARCHAR(350),
    date_comment TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO comments (user_id, post_id, text_comment) 
VALUES 
    (1, 1, 'Roupas de inverno são as melhores!'),
    (2, 1, 'Amo o inverno'),
    (3, 2, 'Roupas de verão são as melhores!'),
    (4, 2, 'Amo o verão'),
    (5, 3, 'Roupas de outono são as melhores!'),
    (6, 3, 'Amo o outono'),
    (7, 4, 'Roupas de primavera são as melhores!'),
    (8, 4, 'Amo a primavera'),
    (9, 5, 'Muito boa essa combinação para festa'),
    (1, 5, 'Roupas de praia são muito divas'),
    (2, 6, 'Simplesmente impecável! Esse look tá um arraso 🔥'),
    (3, 6, 'O estilo tá em outro nível! Amei demais 😍'),
    (7, 7, 'Você sempre entrega tudo no visual! ✨'),
    (4, 7, 'Chique, moderno e cheio de atitude. Amei!'),
    (5, 8, 'Essa combinação ficou perfeita em você! 👏'),
    (6, 8, 'Arrasou demais! Você é uma verdadeira fashionista! 💖'),
    (7, 9, "Essa jaqueta é tudo! Onde você comprou? 😍"),
    (8, 9, "Amei o mix de texturas, super tendência!"),
    (9, 10, "Esse look é puro glamour! Você arrasa sempre! 💫"),
    (1, 10, "Amei a combinação de cores! Super estiloso!"),
    (2, 11, "Esse vestido é um sonho! Onde você encontrou? 🌸"),
    (3, 11, "Você tá linda demais! Amei o look!"),
    (4, 12, "Essa blusa é tudo! Você arrasa no estilo!"),
    (5, 12, "Amei a estampa! Super fashionista!"),
    (6, 13, "Esse look tá perfeito pra festa! Arrasou! 🎉"),
    (7, 13, "Você sempre entrega tudo no visual! ✨"),
    (8, 14, "Essa combinação ficou perfeita em você! 👏"),
    (9, 14, "Arrasou demais! Você é uma verdadeira fashionista! 💖"),
    (10, 15, "Essa paleta de cores tá perfeita pro outono 🍂"),
    (1, 15, "Look comfy e estiloso ao mesmo tempo 💯"),
    (2, 16, "A bota deu um toque poderoso no visual 👢"),
    (3, 16, "Dá aula de estilo todo dia, né? 📚💁‍♀️"),
    (4, 17, "Pinterest deveria te contratar urgente! 🖼️"),
    (22, 17, "Se estilo fosse crime, você já estaria presa 😂"),
    (5, 18, "Metade fashion week, metade sonho 😍"),
    (12, 18, "Qual a inspiração desse look? Amei demais!"),
    (13, 19, "Me ajuda a montar algo parecido? Tô sem ideias 😅"),
    (12, 19, "Você acha que esse look combina com tênis branco também?"),
    (13, 20, "Usaria fácil esse look! Tem link das peças?"),
    (14, 20, "Você é a definição de estilo 😍"),
    (15, 21, "Cada look melhor que o outro, como pode?"),
    (2, 21, "Você transforma qualquer roupa em tendência 👏"),
    (2, 22, "A energia desse visual tá surreal ✨"),
    (3, 22, "Look de milhões 💸"),
    (23, 23, "Essa calça é TUDO! Onde encontro uma igual?"),
    (12, 23, "Amei como o blazer deu um ar sofisticado 👌"),
    (12, 24, "O vestido tá a coisa mais linda, super delicado 💕"),
    (1, 24, "Esse conjunto tá super na moda, amei a vibe!"),
    (2, 25, "Tênis branco e vestido? Combinação perfeita! 👟👗"),
    (3, 25, "Esse look tem a sua cara! Cheio de atitude 💥"),
    (25, 26, "Você tem um estilo único, dá pra ver de longe 😎"),
    (26, 26, "Zero defeitos! Tudo combinando perfeitamente 💫"),
    (27, 27, "Dá pra ver que você entende MUITO de moda 🔥"),
    (28, 27, "Inspirador! Já quero copiar esse estilo 😍"),
    (29, 28, "Tô te denunciando por excesso de beleza e estilo 😅"),
    (30, 28, "Me ensina a ser estilosa assim, por favor 🙏"),
    (31, 29, "Nem o espelho aguenta tanta beleza 🤯"),
    (32, 29, "Você é o próprio moodboard do Pinterest 📌"),
    (33, 30, "A moda agradece sua existência 😍"),
    (34, 30, "Look incrível! Você monta sozinha ou tem stylist?"),
    (35, 31, "Qual app você usa pra editar as fotos? Ficaram lindas!"),
    (36, 31, "Esse look daria super certo numa sessão de fotos profissional!"),
    (37, 32, "Daria certo com acessórios dourados também, né?"),
    (38, 32, "Qual a sua maior inspiração de moda hoje em dia?"),
    (39, 33, "A cara do verão! Look leve e cheio de estilo ☀️🌊"),
    (40, 33, "Esse biquíni tá tudo! A cor valorizou muito você 😍"),
    (41, 34, "Praia + estilo = você arrasando como sempre 🏖️"),
    (42, 34, "Diva solar! Iluminando o feed com esse look 🔆");
    (43, 35, "Chapéu, óculos, biquíni… entregou tudo! 🧢🕶️👙"),
    (44, 35, "Look quentinho e estiloso, a combinação perfeita 🔥🧥"),
    (45, 36, "Frio com personalidade, amei esse casaco demais!"),
    (46, 36, "Essa sobreposição ficou INCRÍVEL 😍"),




