CREATE TABLE comments (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE,
    text_comment VARCHAR(350),
    date_comment TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO comments (user_id, post_id, text_comment) 
VALUES 
    (1, 1, 'Roupas de inverno são as melhores!'),
    (2, 1, 'Amo o inverno'),
    (3, 2, 'Roupas de verão são as melhores!'),
    (4, 2, 'Amo o verão'),
    (5, 3, 'Roupas de outono são as melhores!'),
    (6, 3, 'Amo o outono'),
    (7, 4, 'Roupas de primavera são as melhores!'),
    (8, 4, 'Amo a primavera'),
    (9, 5, 'Muito boa essa combinação para festa'),
    (1, 5, 'Roupas de praia são muito divas'),
    (2, 6, 'Simplesmente impecável! Esse look tá um arraso 🔥'),
    (3, 6, 'O estilo tá em outro nível! Amei demais 😍'),
    (7, 7, 'Você sempre entrega tudo no visual! ✨'),
    (4, 7, 'Chique, moderno e cheio de atitude. Amei!'),
    (5, 8, 'Essa combinação ficou perfeita em você! 👏'),
    (6, 8, 'Arrasou demais! Você é uma verdadeira fashionista! 💖'),
    (7, 9, "Essa jaqueta é tudo! Onde você comprou? 😍"),
    (8, 9, "Amei o mix de texturas, super tendência!"),
    (9, 10, "Esse look é puro glamour! Você arrasa sempre! 💫"),
    (1, 10, "Amei a combinação de cores! Super estiloso!"),
    (2, 11, "Esse vestido é um sonho! Onde você encontrou? 🌸"),
    (3, 11, "Você tá linda demais! Amei o look!"),
    (4, 12, "Essa blusa é tudo! Você arrasa no estilo!"),
    (5, 12, "Amei a estampa! Super fashionista!"),
    (6, 13, "Esse look tá perfeito pra festa! Arrasou! 🎉"),
    (7, 13, "Você sempre entrega tudo no visual! ✨"),
    (8, 14, "Essa combinação ficou perfeita em você! 👏"),
    (9, 14, "Arrasou demais! Você é uma verdadeira fashionista! 💖"),
    (10, 15, "Essa paleta de cores tá perfeita pro outono 🍂"),
    (1, 15, "Look comfy e estiloso ao mesmo tempo 💯"),
    (2, 16, "A bota deu um toque poderoso no visual 👢"),
    (3, 16, "Dá aula de estilo todo dia, né? 📚💁‍♀️"),
    (4, 17, "Pinterest deveria te contratar urgente! 🖼️"),
    (22, 17, "Se estilo fosse crime, você já estaria presa 😂"),
    (5, 18, "Metade fashion week, metade sonho 😍"),
    (12, 18, "Qual a inspiração desse look? Amei demais!"),
    (13, 19, "Me ajuda a montar algo parecido? Tô sem ideias 😅"),
    (12, 19, "Você acha que esse look combina com tênis branco também?"),
    (13, 20, "Usaria fácil esse look! Tem link das peças?"),
    (14, 20, "Você é a definição de estilo 😍"),
    (15, 21, "Cada look melhor que o outro, como pode?"),
    (2, 21, "Você transforma qualquer roupa em tendência 👏"),
    (2, 22, "A energia desse visual tá surreal ✨"),
    (3, 22, "Look de milhões 💸"),
    (23, 23, "Essa calça é TUDO! Onde encontro uma igual?"),
    (12, 23, "Amei como o blazer deu um ar sofisticado 👌"),
    (12, 24, "O vestido tá a coisa mais linda, super delicado 💕"),
    (1, 24, "Esse conjunto tá super na moda, amei a vibe!"),
    (2, 25, "Tênis branco e vestido? Combinação perfeita! 👟👗"),
    (3, 25, "Esse look tem a sua cara! Cheio de atitude 💥"),
    (25, 26, "Você tem um estilo único, dá pra ver de longe 😎"),
    (26, 26, "Zero defeitos! Tudo combinando perfeitamente 💫"),
    (27, 27, "Dá pra ver que você entende MUITO de moda 🔥"),
    (28, 27, "Inspirador! Já quero copiar esse estilo 😍"),
    (29, 28, "Tô te denunciando por excesso de beleza e estilo 😅"),
    (30, 28, "Me ensina a ser estilosa assim, por favor 🙏"),
    (31, 29, "Nem o espelho aguenta tanta beleza 🤯"),
    (32, 29, "Você é o próprio moodboard do Pinterest 📌"),
    (33, 30, "A moda agradece sua existência 😍"),
    (34, 30, "Look incrível! Você monta sozinha ou tem stylist?"),
    (35, 31, "Qual app você usa pra editar as fotos? Ficaram lindas!"),
    (36, 31, "Esse look daria super certo numa sessão de fotos profissional!"),
    (37, 32, "Daria certo com acessórios dourados também, né?"),
    (38, 32, "Qual a sua maior inspiração de moda hoje em dia?"),
    (39, 33, "A cara do verão! Look leve e cheio de estilo ☀️🌊"),
    (40, 33, "Esse biquíni tá tudo! A cor valorizou muito você 😍"),
    (41, 34, "Praia + estilo = você arrasando como sempre 🏖️"),
    (42, 34, "Diva solar! Iluminando o feed com esse look 🔆");
    (43, 35, "Chapéu, óculos, biquíni… entregou tudo! 🧢🕶️👙"),
    (44, 35, "Look quentinho e estiloso, a combinação perfeita 🔥🧥"),
    (45, 36, "Frio com personalidade, amei esse casaco demais!"),
    (46, 36, "Essa sobreposição ficou INCRÍVEL 😍"),
    (47, 37, "Look inverno digno de passarela! 💙"),
    (48, 37, "Mostrando que no frio a gente também lacra 🔥❄️"),
    (49, 38, "Pronta pra brilhar a noite toda! ✨🌙"),
    (50, 38, "Look poderoso! Essa produção tá de tirar o fôlego 😍"),
    (51, 39, "A rainha da balada chegou, e chegou linda 👑"),
    (52, 39, "Muito brilho, muita atitude. Simplesmente perfeita 💃"),
    (53, 40, "Esse vestido tá digno de tapete vermelho 🔥"),
    (54, 40, "Simples, leve e mega estilosa! Amei a vibe 🌸"),
    (55, 41, "Look comfy que não perde o charme ❤️"),
    (56, 41, "Dá vontade de usar esse look todo dia!"),
    (57, 41, "Casual sim, sem graça nunca 😎"),
    (58, 42, "Look do dia aprovado com louvor 👏"),
    (58, 42, "Esse look tá MUITO street, amei demais! 😍"),
    (59, 43, "Estilo urbano que é puro impacto 🖤"),
    (60, 43, "Você é a definição de street style 🔥"),
    (61, 44, "Combinação de cores impecável, tá demais!"),
    (62, 44, "Look street com atitude de sobra 👟🧢"),
    (63, 45, "Pura sofisticação! Look digno de revista ✨"),
    (64, 45, "O clássico nunca sai de moda – e você sabe usar como ninguém 😍"),
    (65, 46, "A elegância mora nos detalhes, e você arrasou!"),
    (66, 46, "Esse look respira classe e estilo 👠"),
    (67, 47, "Visual impecável e atemporal 💼"),
    (1, 47, "Que combinação de cores incrível! Esse look ficou super harmônico 😍🎨"),
    (1, 48, "Você tem um talento único pra montar visuais estilosos e modernos 💫👗"),
    (2, 48, "Amei o contraste das peças, deu um ar super autêntico ao look ✨🖤"),
    (2, 49, "Look super bem pensado, confortável e cheio de personalidade 👌💥"),
    (3, 49, "Você sempre acerta nos detalhes. Esse visual tá impecável 😍🔝"),
    (4, 50, "Cada peça parece ter sido feita sob medida pra você, incrível! 😮‍💨🧵"),
    (5, 50, "A escolha dos acessórios deu um toque final maravilhoso 💎👜"),
    (6, 51, "Dá pra ver que você entende de moda só pelo bom gosto 👏👠"),
    (7, 51, "Um dos melhores looks que vi hoje no feed, sério mesmo 🔥📱"),
    (8, 52, "Essa paleta de cores é a cara da estação! Amei demais 🍂🧡"),
    (9, 52, "Que produção linda! Elegante e moderna na medida certa 👗💖"),
    (10, 53, "Look super versátil, usaria fácil em várias ocasiões 😍✨"),
    (11, 53, "O equilíbrio entre casual e chic ficou perfeito! 🧥👟"),]
    (12, 54, "Tá parecendo capa de revista de moda! Arrasou demais 📰💃"),
    (13, 54, "O look tá tão bom que nem sei o que elogiar primeiro 😍🎯"),
    (14, 55, "Esse outfit transmite confiança e estilo 🖤🔥"),
    (15, 55, "A energia desse look tá surreal, me inspirou real 💫🧡"),
    (16, 56, "Look fresh, leve e super atual. Amei a vibe 🌸🌿"),
    (17, 56, "Que styling perfeito! Essa composição merece destaque 👏📸"),
    (18, 57, "Você consegue transformar qualquer look simples em algo incrível 💥👚"),
    (19, 57, "Seu estilo tem identidade e isso é raro de ver! 😍"),
    (20, 58, "Que bom gosto! Cada detalhe conversa com o outro 🖤💎"),
    (21, 58, "Fashion, ousada e autêntica. Amei o look inteiro 😍👠"),
    (22, 59, "Look comfy com pegada fashionista? Você entrega tudo 🧡🛍️"),
    (23, 59, "Tá lindíssima! Esse visual te valorizou demais 🤍✨"),
    (24, 60, "Já favoritei pra usar como referência no próximo look 👀📌"),
    (25, 60, "Inspiração real de moda no feed hoje 😍🧥"),
    (26, 61, "Essa jaqueta é o auge! Onde você achou essa lindeza? 🧥🤩"),
    (27, 61, "Com esse estilo você comanda qualquer ambiente 👑🔥"),
    (28, 62, "Dá aula de elegância e autenticidade em cada post 🎓💅")
    (29, 62, "Seu visual fala por si: cheio de atitude e bom gosto 👏🖤"),
    (30, 63, "A produção tá perfeita! Super profissional e estilosa 📸✨"),
    (31, 63, "Que vibe maravilhosa! Transmite leveza e segurança 🌟💫"),
    (32, 64, "Roubei essa ideia pro meu próximo look, tá incrível 😍💡"),
    (33, 64, "Look digno de fashion week! Você arrasou demais 👠📸"),
    (34, 65, "Amo como você combina peças básicas com personalidade 🔥💖"),
    (35, 65, "Tá muito fashion, parece saída direto de editorial 😮‍💨🖤"),
    (36, 66, "Um visual criativo, moderno e super bem executado 👏🎨"),
    (37, 66, "Cores, textura, corte… tudo no ponto certo! 🧵👗"),
    (38, 67, "Visual bem construído e cheio de presença! 👀🔥"),
    (39, 67, "Essa composição ficou muito além do básico! Você brilhou 💫💼"),
    (40, 68, "Look com presença! Amei o impacto da produção 😍🖤"),
    (41, 68, "Cada post seu é um banho de inspiração fashion ✨📲"),
    (42, 69, "Que arraso! Mostrando que moda é expressão 💬🧥"),
    (43, 69, "Look super atual e com uma pegada descolada 🤩🧢"),
    (44, 70, "Você dominou a estética urbana com muita elegância 🖤🚶‍♀️"),
    (45, 70, "Ousada na medida certa! Esse look tá incrível 👏🔥"),
    (46, 71, "Super bem equilibrado, confortável e fashion 💡👟"),
    (47, 71, "A silhueta do look ficou linda demais em você 😍📏"),
    (48, 72, "Você realmente sabe como valorizar cada peça 👗👜"),
    (49, 72, "Simplesmente apaixonado(a) nesse look! Você tem um estilo único 🖤✨"),
    (50, 73, "O outfit ficou sofisticado sem perder a essência urbana 🔥🧥"),
    (51, 73, "Consegue ser moderna, elegante e ousada no mesmo look! 💃🔥"),
    (52, 74, "Essa composição tá tão equilibrada que virou minha nova inspiração 💡💖"),
    (53, 74, "Cada peça foi escolhida com tanta precisão, tô impressionado(a) 😍🎯"),
    (54, 75, "Você faz da moda uma arte! Cada post é um quadro 💫🖼️"),
    (55, 75, "Visual perfeito da cabeça aos pés! 🧢👠"),
    (56, 76, "Simples, direto e cheio de atitude. Amei o conceito 💥🧡"),
    (57, 76, "Essa produção tá a cara do streetwear chique! 👟🖤"),
    (58, 77, "Nunca decepciona no estilo! Já virou referência 😍🔝"),
    (59, 77, "O equilíbrio entre ousadia e sofisticação tá surreal! 😮‍💨✨"),
    (60, 78, "Um mix de tendências com identidade, amei demais! 👗🌈"),
    (61, 78, "Como consegue sempre inovar e surpreender no visual? 🔥🧠"),
    (62, 79, "Até o cenário combina com o look! Tudo muito bem pensado 📸🎯"),
    (63, 79, "Cada foto sua vira inspiração pro meu próprio estilo 😍📌"),
    (64, 80, "Você mostra que estilo é uma forma de expressão 💬🧥"),
    (65, 80, "O caimento dessa roupa ficou perfeito em você! 🧵📏"),
    (66, 81, "Que presença! Você domina o look e o ambiente 🔥🖤"),
    (67, 81, "Super fashionista sem parecer forçado. Isso é talento 💅🧠"),
    (68, 82, "Essa produção me ganhou no primeiro olhar 😍🔍"),
    (69, 82, "Look conceito e execução perfeita 👌💡"),
    (70, 83, "Ouse mais! O resultado fica incrível em você ✨🖤"),
    (71, 83, "As combinações que você faz são sempre surpreendentes 💖👚"),
    (72, 84, "Dá vontade de copiar esse look agora mesmo! 🧥🛍️"),
    (73, 84, "Acessórios incríveis! Deram vida ao visual 💎📿"),
    (74, 85, "A vibe dessa foto com esse look ficou TUDO 🧡📸"),
    (75, 85, "É sobre ter estilo e saber usar, e você sabe! 👏🔥"),
    (76, 86, "Visual criativo, moderno e com alma 😍🖤"),
    (77, 86, "Tudo tão bem encaixado, parece editorial de moda 😮‍💨📰"),
    (78, 87, "Você inspira com cada detalhe desse visual 💡💫"),
    (79, 87, "A combinação de tecidos ficou perfeita! 👗🧵"),
    (80, 88, "Totalmente fashion sem perder o conforto. Isso sim! 😍👟"),
    (81, 88, "O jogo de cores ficou sensacional! Super original 🎨🧡"),
    (82, 89, "Eu só queria metade desse bom gosto kkkkk 😂💅"),
    (83, 89, "Esse visual tem um quê de ousadia elegante 💼🔥"),
    (84, 90, "O look tá tão bom que eu salvei aqui como referência 📲📌")
    (85, 90, "Um arraso do início ao fim. Amei a composição 👏💖"),
    (86, 91, "Look simples com presença de sobra! ✨🖤"),
    (87, 91, "Essa é a definição de estar bem vestida 😍👗"),
    (88, 92, "As camadas desse look ficaram incríveis. Super estilosa! 🧥🧣"),
    (89, 92, "Você entrega conteúdo de moda com alma 💫🎬"),
    (90, 93, "Gosto tanto desse estilo que já virou meu preferido! ❤️👟"),
    (91, 93, "Essa produção tá gritando “confiança”! Adorei 🧡🔥"),
    (92, 94, "O toque urbano nesse look fez toda a diferença 🧢🖤"),,
    (93, 94, "Tá uma visão de tão linda com esse visual 😍🌟"),
    (94, 95, "Essa harmonia entre peças e acessórios ficou perfeita 💎🧥"),
    (95, 95, "O look é top, mas sua atitude é o que dá o brilho final 😎💫"),
    (96, 96, "Achei tudo muito bem coordenado. Parabéns pelo bom gosto! 👏✨"),
    (97, 96, "Um visual cheio de força, personalidade e elegância 🔥👑"),
    (98, 97, "Você tem o poder de transformar qualquer look básico em algo extraordinário 💥✨"),
    (99, 97, "Esse look exala autenticidade, não tem como não notar! 😍🌟"),
    (1, 98, "A vibe desse visual tá muito Pinterest 💻📌"),
    (2, 98, "Toda fashionista deveria ver esse post, sério! 👗💬"),
    (3, 99, "Que harmonia! Estilo e presença num mesmo clique 📸🔥"),
    (4, 99, "Cada detalhe dessa composição mostra sua identidade 🧠🖤"),
    (5, 100, "Seu senso de estilo é realmente único, parabéns! ✨💖"),
    (6, 100, "Essa peça central é maravilhosa! Super tendência 👚📈"),
    (7, 101, "Look comfy com toque fashion? Isso é tudo! 😍🛋️"),
    (8, 101, "Você não segue tendências, você cria! 👑🔥"),
    (9, 102, "Me ensina a montar um visual assim? Perfeita demais 💅📚"),
    (10, 102, "Estilo e autoestima andam juntos aqui! ❤️‍🔥👗"),
    (11, 103, "Uma explosão de estilo, criatividade e confiança 💥💡"), 
    (12, 103, "Nunca vi uma combinação tão bem pensada quanto essa! 👌🖤"),
    (13, 104, "Isso sim é saber se vestir com atitude 💬🔥"),
    (14, 104, "Cada detalhe desse visual tá gritando personalidade! 😍💥"),
    (15, 105, "A pegada minimalista deixou tudo ainda mais elegante 🤍🧥"),
    (16, 105, "Que produção estilosa! Dá até vontade de montar um igual 👟🧢"),,
    (17, 106, "Esse blazer com jeans ficou incrível demais! 🧥👖"),
    (18, 106, "Esse equilíbrio entre peças largas e justas ficou ótimo 🔄🖤"),
    (19, 107, "Você arrasou no look e na pose! Tudo perfeito 📸🔥"),
    (20, 107, "Um toque de ousadia nunca é demais e você provou isso! 💅💣"),
    (21, 108, "Esse visual ficou harmônico da cabeça aos pés 👠🧢"),
    (22, 108, "Tá com cara de capa de revista! Linda demais 😍📰"),
    (23, 109, "Sua identidade sempre aparece nos seus looks, e isso é incrível ✨🖤"),
    (24, 109, "Esse look tá tão alinhado com sua vibe, amei! 💫🎯"),
    (25, 110, "Tá um arraso do cabelo ao sapato! 👠💇‍♀️"),
    (26, 110, "Visual equilibrado, bonito e cheio de estilo 👏💼"),
    (27, 111, "Essa produção tem impacto, elegância e muita personalidade 🔥🎬"),
    (28, 111, "Look prático, estiloso e super atual! 😍👜"),
    (29, 112, "Sabe quando tudo dá certo? Foi o caso desse look 👏✨"),
    (30, 112, "Você carrega o look com tanta confiança! Isso é lindo de ver 💖🖤"),
    (31, 113, "Amei a mistura de peças clássicas com toques modernos 👗⚡"),
    (32, 113, "Esse visual tá vibrante, estiloso e super inspirador 🌈📌"),
    (33, 114, "Dá pra ver que foi tudo feito com muito cuidado e estilo 💅🧵"),
    (34, 114, "Esse fundo combinou demais com o look, tudo perfeito! 📸🌆"),
    (35, 115, "Parece uma produção de cinema de tão bem feita 🎬🎞️"),
    (36, 115, "Esse outfit me deixou apaixonado(a), sério! 🖤💘"),
    (37, 116, "Você tá servindo moda com personalidade em cada post 👑🧥"),
    (38, 116, "Look do dia? Mais parece look do ano! 😍🔥"),
    (39, 117, "Essa vibe tá maravilhosa, quero copiar tudo! ✨📋"),
    (40, 117, "Um estilo que equilibra conforto e elegância com perfeição 👟👜"),
    (77, 87, 'Look comfy e fashion ao mesmo tempo 😍✨'),
    (78, 88, 'Essa composição ficou chiquérrima! 💅💎'),
    (79, 89, 'Cada detalhe desse visual está impecável! 🔥🖤'),
    (80, 90, 'Simplicidade com toque de sofisticação 👌🌷'),
    (81, 91, 'O street style nunca esteve tão em alta! 🏙️👟'),
    (82, 92, 'Mix de estampas que funcionou perfeitamente 😍👗'),
    (83, 93, 'Cores vibrantes que contagiam! 🌈💖'),
    (84, 94, 'Visual urbano com identidade! 🙌🧢'),
    (85, 95, 'Trendy, atual e super estilosa! 🧡🖤'),
    (86, 96, 'Esse look poderia estar em uma revista de moda! 📸✨'),
    (87, 97, 'Inspiração pura! Cada dia um desfile diferente 💃🔥'),
    (88, 98, 'Look comfy e autêntico, adorei! 😌🧣'),
    (89, 99, 'Totalmente fashion week vibes! 🧥🖤'),
    (90, 100, 'Estilo fresh e moderno! 🌿🧼'),
    (91, 101, 'Combinação ousada e perfeita 😍🧡'),
    (92, 102, 'Seu guarda-roupa deve ser um sonho! 💭👗'),
    (93, 103, 'Look minimalista cheio de personalidade! 👌🖤'),
    (94, 104, 'Acessórios on point! 👜👓'),
    (95, 105, 'Amei o contraste desse look! 🎨✨'),
    (96, 106, 'Look com toque artístico e fashion 😍🖌️'),
    (97, 107, 'Elegância natural, sem esforço 👏💫'),
    (98, 108, 'Look romântico e moderno ao mesmo tempo 💕🌸'),
    (99, 109, 'Essa bota é tudo! Arrasou demais 🖤👢'),
    (100, 110, 'Estilo urbano com alma fashionista 💣🏙️'),
    (100, 111, 'Super criativa a combinação! 🎨🖤'),
    (100, 112, 'Você transforma qualquer roupa em tendência! 🔝💖'),
    (100, 113, 'Estilo comfy chic ativado! 😌👑'),
    (100, 114, 'Look poderoso e autêntico 💥🔥'),
    (100, 115, 'Ousadia com elegância, amei! 😍🧡'),
    (100, 116, 'Look tão leve quanto estiloso ☁️✨'),
    (100, 117, 'Chic & cool na medida certa 💁‍♀️🖤'),
    (100, 118, 'Amando essa estética clean! 🤍👚'),
    (100, 119, 'Visual despojado com toque de luxo! 💎👟'),
    (100, 120, 'Estilo que inspira! Continue assim 😍💫'),
    (100, 121, 'Color blocking maravilhoso! 🔵🟡'),
    (100, 122, 'Essa vibe fashion retrô tá incrível! 📼👖'),
    (100, 123, 'Look que brilha sem esforço! 🌟✨'),
    (100, 124, 'Essa combinação tá um escândalo de linda! 😱💖'),
    (100, 125, 'Mistura de texturas perfeita! 🧵🧥'),
    (100, 126, 'Super fashionista com esse look all black 🖤🖤'),
    (100, 127, 'Elegância moderna em cada detalhe 👠💄'),
    (100, 128, 'Que arraso! O look grita atitude 💥🖤'),
    (100, 129, 'Você nasceu pra brilhar na moda ✨😎'),
    (100, 130, 'Estilo próprio e marcante! 👏🔥'),
    (100, 131, 'Tudo nesse look combina contigo! 👌💛'),
    (100, 132, 'Esse outfit é um verdadeiro statement! 💣🖤'),
    (100, 133, 'A energia desse look é única! 🌈❤️'),
    (100, 134, 'Super criativa e ousada na escolha 💡👚'),
    (100, 135, 'Look pra copiar já! 📌✨'),
    (100, 136, 'Chique e descolada como sempre! 😍💼'),